name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # This is required for actions/checkout and pushing to gh-pages
      pages: write        # This is required for deploying to GitHub Pages
      id-token: write     # This is required for GitHub Pages authentication

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Node.js (you can specify a specific Node version if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies and build
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          cp -r public/* dist/
        env:
          BASE_URL: ${{ github.event.repository.name }}

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Adjust this if your build output is in a different directory
          force_orphan: true  # This creates a fresh gh-pages branch each time
          enable_jekyll: false  # This prevents GitHub from processing the site with Jekyll
